### ISSUE TITLE
选项 layout 错误

### ISSUE THREAD

**Issue by lychees** [casimir-crystal/saki-project#1]
![telegram-cloud-photo-size-1-5071276751103044421-x](https://user-images.githubusercontent.com/2507027/122525930-53fb4480-d04c-11eb-9c8d-e07d06929fe8.jpg)

Day 0 选了第一个回到选项窗口 UI 排版会混乱。

**Comment by CaTcatM200** [comment]
https://github.com/casimir-crystal/saki-project/commit/8123c08b9bbca3a7fa67aedb71d102d84a268fd7 
Fixed.
